// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/helloworld.proto

package com.rocka;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rocka.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
